os:linux


language: c

compiler:gcc
addons:
    apt:
        packages:
            - libtool
            - autoconf
            - automake
            - make

install:
    
before_script:
    - sh autogen.sh
    - ./configure

script:
    # When using the bison from Debian we need to tell that bison where
    # to e code.  Not.
    - make -j4
    - make check -j4
